version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py makemigrations
          name: MakeMigrations
      - run:
          command: ./manage.py migrate
          name: Migrate
      - run:
          command: ./manage.py collectstatic --noinput
          name: CollectStatic
      - run:
          command: python -m black --check .
          name: StyleCheck
      - run:
          command: python -m flake8 .
          name: FormatCheck
      - run:
          command: python -m coverage run --source=restaurant,user manage.py test
          name: Test
      - run:
          command: python -m coveralls
          name: Coveralls

workflows:
  main:
    jobs:
      - build-and-test
